services:
  gtu-users-management-service:
    build: .
    container_name: gtu-users-management-service
    environment:
      - EUREKA_SERVER_HOST=discovery-server
      - EUREKA_SERVER_PORT=8761
      - DB_HOST=postgres-users
      - DB_PORT=5432
      - DB_NAME=gtu_users_db
      - DB_USER=user
      - DB_PASSWORD=password
      - SERVER_PORT=0
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL}
    networks:
      - shared_network
networks:
  shared_network:
    external: true